### ISSUE TITLE
parallel building of plugins fails to upload all built plugins

### ISSUE THREAD

**Issue by evgeni** [theforeman/jenkins-jobs#140]
Ohai,

when you trigger `foreman-packaging-deb-nightly-release` with multiple changed plugins (like happened in https://ci.theforeman.org/job/foreman-packaging-deb-nightly-release/26/), it correctly *builds* all changed plugins, but the upload happens only for one plugin.

I think this is because we end up calling `rsync_to_debian_release` only once, but the packages actually live in different folders on disk (thanks to Jenkins' `dir()` creating temp folders for us when called with `parallel`).

I wonder why we didn't see this for non-plugins yet.

**Comment by ehelms** [comment]
Proposed fix -- https://github.com/theforeman/jenkins-jobs/pull/142
