### ISSUE TITLE
Switch pipelines to using Alma

### ISSUE THREAD

**Issue by ehelms** [theforeman/jenkins-jobs#472]

**Comment by ekohl** [comment]
Pipelines currently run both AlmaLinux and CentOS Stream:
https://github.com/theforeman/jenkins-jobs/blob/557f2ff5bb70329265b550574952014375a69dd1/theforeman.org/pipelines/vars/foreman/nightly.groovy#L28-L41

We will need to drop `centos8-stream` from files like that. Those files are all in [theforeman.org/pipelines/vars](https://github.com/theforeman/jenkins-jobs/tree/master/theforeman.org/pipelines/vars).

**Comment by archanaserver** [comment]
I noticed pulpcore also run only on CentOS Stream rn. https://github.com/theforeman/jenkins-jobs/blob/557f2ff5bb70329265b550574952014375a69dd1/theforeman.org/pipelines/vars/pulpcore/3.39.groovy#L4-L9
If I want to add AlmaLinux there as well, how would I know what is supported for this specific? Or if there is any additional steps I should keep in mind? @ekohl @ehelms

**Comment by ekohl** [comment]
It should be supported, because we allow users to run Katello (which includes Pulp) to run on AlmaLinux. In fact, we even run our Katello CI pipelines on AlmaLinux so implicitly it's already tested.

**Comment by archanaserver** [comment]
Thanks!

**Comment by archanaserver** [comment]
https://github.com/theforeman/jenkins-jobs/pull/474

**Comment by archanaserver** [comment]
https://github.com/theforeman/jenkins-jobs/pull/475
